# Generated by Django 4.1.3 on 2023-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='categories',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
