# Generated by Django 4.1.3 on 2023-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='shop')),
                ('category1', models.CharField(choices=[('electronics', 'ELECTRONICS'), ('shoes', 'SHOES'), ('tops', 'TOPS'), ('trousers', 'TROUSERS'), ('jewellries', 'JEWELLRIES')], max_length=100)),
                ('category2', models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('all', 'ALL')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('totalcash', models.IntegerField(max_length=200)),
                ('payment', models.CharField(choices=[('cash', 'CASH'), ('transfer', 'TRANSFER'), ('card', 'CARD')], max_length=200)),
            ],
        ),
    ]
